title: Adapt
email: adapt@internews.org
description: >-
  The Advocating for Data Accountability, Protection, and Transparency (ADAPT), a project of Internews, is building a coordinated advocacy effort to promote rights-respecting privacy policies and help internet users understand what protections currently exist to keep their data, and themselves, safe online.
baseurl: ""
url: "/"
twitter_username:
github_username:

plugins:
  - jekyll-feed

collections:
  authors:

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
